use_frameworks!

target 'TransitionRouter_Example' do
  pod 'TransitionRouter', :path => '../'

  target 'TransitionRouter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
  end

end
